### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by CA1012** [FGMEMBERS/757-200#1]
Will FG ever get the 757-300? that thing is long and it deserves to be represented.

**Comment by legoboyvdlp** [comment]
Well, tikibar said 'don't hold your breath'. Why don't you make it yourself?

**Comment by FGDATA** [comment]
@CA1012 @legoboyvdlp 
Haha 
this is funny. 

Falcon, there is a good chance that FG sometime gets a B753, but certainly someone will need to work on it. Tikibar certainly is a very experienced boeing developer, and his response, If I get him correctly means, this is not in his immediate plans. 

So for now. Sit tight and wait. Luckily there are so many other planes to enjoy while years pass by till this aircraft gets ever made.

**Comment by FGDATA** [comment]
For now, I close this issue, because really, it does not mean that there is something to be fix for the B752
